### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jshwlkr** [Varying-Vagrant-Vagrants/custom-site-template#1]
Could we get a little more verbose documentation? I'm not quite sure how to actually use a custom site template in conjunction with VVV.

**Comment by jeremyfelt** [comment]
Hi @jshwlkr, thanks for opening an issue.

The best documentation available now for this is the combination of the [vvv-config.yml page](https://varyingvagrantvagrants.org/docs/en-US/vvv-config/) and the [README in this repository](https://github.com/Varying-Vagrant-Vagrants/custom-site-template/blob/master/README.md).

One of our objectives is to continue improving the documentation for VVV and surrounding projects, so more will be coming in the near future. Please open an issue on the main [VVV repository](https://github.com/Varying-Vagrant-Vagrants/VVV) if you have more ideas.
